# Generated by Django 3.2.7 on 2021-09-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210909_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-name'], 'verbose_name': '图书类', 'verbose_name_plural': '图书类'},
        ),
    ]
